---
abstract: 'A framework for adding additional metadata to Moose classes'
author:
  - 'Code and Design originally by Jonathan Rockway in the Ernst module, '
build_requires:
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-MetaDescription
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.4
tests: t/*.t
version: 0.03
