---
abstract: 'A framework for adding additional metadata to Moose classes'
author:
  - 'Code and Design originally by Jonathan Rockway in the Ernst module, '
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Exception: 0
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.05'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-MetaDescription
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0.4
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
